[package]
name = "storm-daenerys-front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
egui_extras = { version = "0.22.0", features = ["svg"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
